x-api_template: &api_template
  image: cicerocg/rinha-v1:v3.0
  platform: linux/amd64
  networks:
    - backend
    - payment-processor
  depends_on:
    postgres:
      condition: service_healthy
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: "100MB"

services:
  api01:
    <<: *api_template
    hostname: api01
  
  api02:
    <<: *api_template
    hostname: api02
  
  postgres:
    image: postgres:15-alpine
    hostname: postgres
    command: >-
      postgres -c max_connections=400
               -c shared_buffers=64MB
               -c synchronous_commit=off
               -c fsync=off
               -c full_page_writes=off
               -c wal_level=minimal
               -c max_wal_senders=0
               -c checkpoint_timeout=30min
               -c log_min_duration_statement=-1
    environment:
      POSTGRES_DB: PaymentsDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d PaymentsDB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    depends_on:
      - api01
      - api02
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  backend:
  payment-processor:
    external: true